services:
  - type: web
    name: family-album-backend
    env: docker
    plan: free
    buildCommand: "./mvnw package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: family_album_db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: family_album_db
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: family_album_db
          property: password
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m"
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health
    autoDeploy: false

databases:
  - name: family_album_db
    plan: free
    ipAllowList: []
